# Generated by Django 5.1 on 2024-10-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='customer_id',
        ),
    ]
