# Generated by Django 5.1.2 on 2024-11-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_product_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
