# Generated by Django 5.1 on 2025-01-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_orderitem_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cashier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
